import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { Inter } from "next/font/google";
import { cn } from "~/lib/utils";
import LenisProvider from "~/components/LenisProvider";
import TopNav from "~/components/navigation/TopNav";
import { Suspense } from "react";
import LoadingScreen from "~/components/welcome/LoadingScreen";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <LenisProvider>
          <body
            className={cn(
              "font-inter mx-auto w-full max-w-[1440px] bg-gray-950 text-white",
              inter.variable,
            )}
          >
            <TopNav />
            <Suspense fallback={<LoadingScreen />}>{children}</Suspense>
          </body>
        </LenisProvider>
      </html>
    </ClerkProvider>
  );
}
